# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
  "username":"admin",
  "password":"123456"
}

###
POST http://127.0.0.1:8000/movie
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "title" : "Interstellar",
  "director": "Christopher Nolan",
  "year": 2014,
  "rating": 8.2,
  "genres": "Ciencia ficción"
}